### ISSUE TITLE
Complete origin on miRNA

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel-tools#15]
Most miRNA can be written with `g(HGNC:YFG) transcribedTo m(HGNC:YFG)` so the inference of the central dogma should also make these edges. 

I'm also curious about miRNA's themselves, since there's a differentiation between a "premature" and a "mature" sequence. Does the premature sequence count as an RNA and not an miRNA?

Thoughts @cebel, @dexterpratt?

**Comment by dexterpratt** [comment]
> On Mar 2, 2017, at 4:25 AM, Charles Tapley Hoyt <notifications@github.com> wrote:
> 
> Most miRNA can be written with g(HGNC:YFG) transcribedTo m(HGNC:YFG) so the inference of the central dogma should also make these edges.
> 
> 

I'm including some excerpts from Wikipedia to clarify my statements.

Genes transcribe to miRNAs

But the genes in question are not the protein coding genes, they are sections of DNA that code miRNAs, although they may be nearby or within protein coding genes.

miRNA genes are usually transcribed by RNA polymerase II (Pol II).[55][56] The polymerase often binds to a promoter found near the DNA sequence, encoding what will become the hairpin loop of the pre-miRNA. 

Further:

As many as 40% of miRNA genes may lie in the introns or even exons of other genes.[50] These are usually, though not exclusively, found in a sense orientation,[51][52] and thus usually are regulated together with their host genes.[50][53][54]

The nomenclature / namespace, is therefor separate from protein coding gene namespaces such as HGNC. Here is a long section from Wikipedia:

Under a standard nomenclature system, names are assigned to experimentally confirmed miRNAs before publication.[47][48] The prefix "miR" is followed by a dash and a number, the latter often indicating order of naming. For example, miR-124 was named and likely discovered prior to miR-456. A capitalized "miR-" refers to the mature form of the miRNA, while the uncapitalized "mir-" refers to the pre-miRNA and the pri-miRNA, and "MIR" refers to the gene that encodes them.[49]

miRNAs with nearly identical sequences except for one or two nucleotides are annotated with an additional lower case letter. For example, miR-124a is closely related to miR-124b.

Pre-miRNAs, pri-miRNAs and genes that lead to 100% identical mature miRNAs but that are located at different places in the genome are indicated with an additional dash-number suffix. For example, the pre-miRNAs hsa-mir-194-1 and hsa-mir-194-2 lead to an identical mature miRNA (hsa-miR-194) but are from genes located in different genome regions.

Species of origin is designated with a three-letter prefix, e.g., hsa-miR-124 is a human (Homo sapiens) miRNA and oar-miR-124 is a sheep (Ovis aries) miRNA. Other common prefixes include 'v' for viral (miRNA encoded by a viral genome) and 'd' for Drosophila miRNA (a fruit fly commonly studied in genetic research).

When two mature microRNAs originate from opposite arms of the same pre-miRNA and are found in roughly similar amounts, they are denoted with a -3p or -5p suffix. (In the past, this distinction was also made with 's' (sense) and 'as' (antisense)). However, the mature microRNA found from one arm of the hairpin is usually much more abundant than that found from the other arm,[2] in which case, an asterisk following the name indicates the mature species found at low levels from the opposite arm of a hairpin. For example, miR-124 and miR-124* share a pre-miRNA hairpin, but much more miR-124 is found in the cell.


So an example bel statement would be:

g(hsa-miR-181d) transcribedTo m(hsa-miR-181d)

We could express this with our species namespace convention - m(hsa:miR-181d)

-----

transcription factors may affect both protein coding genes and miRNAs

and of course, a given miRNA can suppress the translation of specific protein coding rna to their proteins, i.e.

m(X) =| p(Y)

> I'm also curious about miRNA's themselves, since there's a differentiation between a "premature" and a "mature" sequence. Does the premature sequence count as an RNA and not an miRNA?
> 
> 

no, the standard “RNA” for r(X) designates a tRNA, “transferRNA”, meaning RNA destined for translation to protein, rather than miRNA binding to genes and suppressing their transcription.

This is a very similar to the issue of handling processing of proteins required to their “final” forms.Proteins, once produced by the ribosomes, typically need many kinds of processing to produce their active form. Pruning, glycosylating, adding lipid “tails” (like the farnsylation of HRAS), chaperone help with folding, etc.  

But the literature knows these details for specific paths required for a given protein in relatively (maybe extremely) few cases.

This has been an issue for years. Past bel practice (at least in my hands when at Selventa) has been to simply assert causal relationships between modification states and protein activity, just like states induced later during signalling.

My tendency would be to do the same thing with miRNAs - things that interfere with maturation of a given miRNA affect its abundance. In many cases these “things” may often be only known as emprical causal effects (->, -|), the full mechanism unknown.

**Comment by cthoyt** [comment]
Dexter, thanks for the commentary. I had this on the back burner for a bit but I really appreciate the help and now I've solved the problem

**Comment by dexterpratt** [comment]
BTW, I made an important mistake in my commentary.

I meant to say “messenger” RNA (mRNA) when I said “transfer” RNA.  Sorry, just caught that now, can’t think how I got that backwards.

**Comment by cthoyt** [comment]
Haha I think I also knew what you meant and didn't notice either :)

I've edited your old post to be correct in case anyone else reads it

**Comment by dexterpratt** [comment]
In films and comic books I think that is known as “retcon” :-)

**Comment by cthoyt** [comment]
UGHH retcons are such a bad plot device
