### ISSUE TITLE
Additional network summary ideas

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel-tools#54]
From Stubbi:

api of scaiview - top 10 genes/proteins in comorbidities
how often publications are mentioned with both diseases

**Comment by ddomingof** [comment]
It would be cool to allow the user in the summary to see how much overlap there is between that network and the others one loaded... (only if they want to do the analysis since I guess it would be a little expensive). Similarly, you could also check for common pubmed ids or authors as edge info.
Easy to implement and another more feature
